some_practise/insta_killer/insta_killer/insta_app/urls.py
from django.urls import path

from . import views

app_name = "insta_app"

urlpatterns = [
    path('', views.main, name="main"),
    path('upload/', views.upload, name="upload"),
    path("pictures/", views.pictures, name="pictures"),
    path("pictures/remove/<int:pic_id>", views.remove_picture, name="remove"),
    path("pictures/edit/<int:pic_id>", views.edit_picture, name="edit"),
]

some_practise/insta_killer/insta_killer/insta_killer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("insta_app.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

some_practise/insta_killer/insta_killer/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import RegisterView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        LoginView.as_view(
            redirect_authenticated_user=True,
            template_name="users/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
]

some_practise/insta_killer/insta_killer/insta_app/models.py
import os
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

def update_filename(instance, filename):
    upload_to = 'uploads'
    ext = filename.split('.')[-1]
    filename = f"{uuid4().hex}.{ext}"
    return os.path.join(upload_to, filename)

class Picture(models.Model):
    description = models.CharField(max_length=350)
    path = models.ImageField(upload_to="uploads")
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

some_practise/insta_killer/insta_killer/users/models.py
from django.db import models

# Create your models here.

some_practise/insta_killer/insta_killer/insta_app/forms.py
from django.forms import ModelForm, ImageField, FileInput, CharField, TextInput

from .models import Picture


class PictureForm(ModelForm):
    description = CharField(max_length=350, widget=TextInput(attrs={"class": "form-control"}))
    path = ImageField(widget=FileInput(attrs={"class": "form-control"}))
    
    
    class Meta:
        model = Picture
        fields = ["description", "path"]

some_practise/insta_killer/insta_killer/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "First name"}))

    last_name = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Last name"}))
    username = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Username"}))
    email = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Email"}))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Password"}))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Confirm Password"}))


    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Username"}))
    password = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "Password"}))



    class Meta:
        model = User
        fields = ['username', 'password']

some_practise/insta_killer/insta_killer/insta_app/views.py
import os
from django.conf import settings
from django.contrib.auth.models import login_required
from django.shortcuts import render, redirect

from .forms import PictureForm
from .models import Picture
# Create your views here.
def main(request):
    return render(request, "insta_app/index.html", context={"title": "Killer Instagram"})

@login_required
def upload(request):
    form = PictureForm(instance=Picture())
    if request.method == "POST":
        form = PictureForm(request.POST, request.FILES, instance=Picture())
        if form.is_valid():
            pic = form.save(commit=False)
            pic.user = request.user
            pic.save()
            return redirect(to="insta_app:main")
    return render(request, "insta_app/upload.html", context={"title": "Killer Instagram", "form": form})


@login_required
def pictures(request):
    pictures = Picture.objects.filter(user=request.user).all()
    return render(request, "insta_app/pictures.html", context={"title": "Killer Instagram", "pictures": pictures})


@login_required
def remove_picture(request, pic_id):
    pic = Picture.objects.filter(user=request.user)
    try:
        os.unlink(os.path.join(settings.MEDIA_ROOT, str(pic.first().path)))
    except OSError as e:
        print(e)
    pic.delete()
    return redirect(to="insta_app:pictures")


@login_required 
def edit_picture(request, pic_id):
    if request.method == "POST":
        description = request.POST["description"]
        Picture.objects.filter(pk=pic_id, user=request.user).update(description=description)
        return redirect(to="insta_app:pictures")
    
    picture = Picture.objects.filter(pk=pic_id, user=request.user).first()
    ctx = {"title": "Killer Instagram", "picture": picture}
    return render(request, "insta_app/edit.html", context=ctx)

some_practise/insta_killer/insta_killer/users/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.contrib import messages

from .forms import RegisterForm
# Create your views here.

class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/register.html'
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='appquote:main')
        return super(RegisterView, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": self.form_class()})
                        
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f"Your account has been created successfully: {username}")
            return redirect(to='users:login')
        
        return render(request, self.template_name, {"form": form})

some_practise/insta_killer/insta_killer/insta_app/templates/insta_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ tittle }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'insta_app:pictures' %}">Pictures</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'insta_app:upload' %}">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Create account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li><li class="nav-item">
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

some_practise/insta_killer/insta_killer/insta_app/templates/insta_app/edit.html
{% extends "insta_app/base.html"%}

{% block content %}
<h1>Edit your picture</h1>
<form action='{% url 'insta_app:edit' picture.id %}' method="post">
  {% csrf_token %} 
  <img src="/media/{{picture.path}}" class="card-img-top" alt="...">
  <div class="mb-3">
    <label class="form-label">Description</label>
    <input type="text" class="form-control" value="{{picture.description}}" name="description">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

some_practise/insta_killer/insta_killer/insta_app/templates/insta_app/index.html
{% extends "insta_app/base.html"%}

{% block content %}
    <h1>Insta Killer</h1>
{% endblock %}

some_practise/insta_killer/insta_killer/insta_app/templates/insta_app/pictures.html
{% extends "insta_app/base.html"%}

{% block content %}
<h1>Your pictures</h1>
<div class="row">
    {% for picture in pictures %}
    <div class="card" style="width: 18rem;">
        <img src="/media/{{picture.path}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{picture.path}}</h5>
            <p class="card-text">
                {{picture.description}}
            </p>
            <a href="{% url 'insta_app:edit' picture.id %}" class="btn btn-warning">Edit</a>
            <a href="{% url 'insta_app:remove' picture.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

some_practise/insta_killer/insta_killer/insta_app/templates/insta_app/upload.html
{% extends "insta_app/base.html"%}

{% block content %}
<form action='{% url 'insta_app:upload' %}' method="post" enctype="multipart/form-data">
    {% csrf_token %} 
  <div class="mb-3">
    <label class="form-label">Description</label>
    {{ form.description }}
  </div>
  <div class="mb-3">
    <label class="form-label">File</label>
    {{ form.path }}
  </div>
  <button type="submit" class="btn btn-primary">Upload</button>
</form>
{% endblock %}

some_practise/insta_killer/insta_killer/users/templates/users/login.html
{% extends 'insta_app/base.html' %}

{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    <span>{{ form.non_field_errors }}</span>
</div>

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

{% endblock  %}

some_practise/insta_killer/insta_killer/users/templates/users/logout.html
{% extends 'insta_app/base.html' %}

{% block content %}

<h1>Thank you!</h1>

{% endblock  %}

some_practise/insta_killer/insta_killer/users/templates/users/register.html
{% extends 'insta_app/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>First Name</label>
                        {{ form.first_name }}
                    </div>
                    <span>{{ form.errors.first_name }}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Last Name</label>
                        {{ form.last_name }}
                    </div>
                    <span>{{ form.errors.last_name }}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Username</label>
                        {{ form.username }}
                    </div>
                    <span>{{ form.errors.username }}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Email</label>
                        {{ form.email }}
                    </div>
                    <span>{{ form.errors.Email }}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Password</label>
                        {{ form.password1 }}
                    </div>
                    <span>{{ form.errors.password1 }}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Confirm Password</label>
                        {{ form.password2 }}
                    </div>
                    <span>{{ form.errors.password2 }}</span>
                </div>
            </div>
            <div class="form-group mt-4 mb-1">
                <button type="submit" class="btn btn-success">Sign Up</button>
            </div>
        </form>
    </div>
</div>
{% endblock  %}