homework/quotes/appquote/urls.py
from django.urls import path

from . import views

app_name = 'appquote'

urlpatterns = [
    path('', views.main, name='main'),
    path('addtag/', views.addtag, name='addtag'),
    path('addauthor/', views.addauthor, name='addauthor'),
    path('addquote/', views.addqoute, name='addquote'),
    path("author/<str:fullname>", views.author_page, name="author"),
    path("tag/<str:tag>", views.tag_page, name="tag")
]

homework/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('appquote.urls')),
    path("users/", include("users.urls")),
] 

homework/quotes/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

homework/quotes/appquote/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.name}'


class Author(models.Model):
    fullname = models.CharField(max_length=100, unique=True)
    born_date = models.CharField(max_length=150, null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return f'{self.fullname}'


class Quote(models.Model):
    text = models.TextField(unique=True, null=False)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text}: {self.author}, {self.tags}"

    def show_quote_text(self):
        return self.text

    def show_quote_author(self):
        return self.author

    def show_quote_tags(self):
        tag_obj = self.tags.all()
        return tag_obj

homework/quotes/users/models.py
from django.db import models

# Create your models here.

homework/quotes/appquote/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField

from .models import Tag, Author, Quote


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=250, widget=TextInput())
    born_date = CharField(widget=TextInput())
    born_location = CharField(widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    text = CharField(max_length=500, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Quote
        fields = ['text', 'author']
        exclude = ['tags']

homework/quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

homework/quotes/appquote/views.py
from collections import Counter

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, AuthorForm, QuoteForm
from .models import Tag, Author, Quote


def main(request):
    quotes = Quote.objects.all()
    all_tags = []
    most_popular_tag = []
    for el in quotes:
        for tag in el.show_quote_tags():
            all_tags.append(tag)
    top_tags = Counter(all_tags).most_common(10)
    for top in top_tags:
        most_popular_tag.append(top[0])
    paginator = Paginator(quotes, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "appquote/index.html",
                  context={"quotes": quotes, "most_popular_tag": most_popular_tag, 'page_obj': page_obj})


@login_required
def addtag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='appquote:main')
        else:
            return render(request, 'appquote/addtag.html', {'form': form})

    return render(request, 'appquote/addtag.html', {'form': TagForm()})


@login_required
def addauthor(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='appquote:main')
        else:
            return render(request, 'appquote/addauthor.html', {'form': form})

    return render(request, 'appquote/addauthor.html', {'form': AuthorForm()})


@login_required
def addqoute(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

                return redirect(to='appquote:main')
        else:
            return render(request, 'appquote/addquote.html', {"tags": tags, "authors": authors, 'form': form})

    return render(request, 'appquote/addquote.html', {"tags": tags, "authors": authors, 'form': QuoteForm()})


def author_page(request, fullname):
    authors = get_object_or_404(Author, fullname=fullname)

    return render(request, "appquote/author.html", {"author": authors})


def tag_page(request, tag):
    tags = get_object_or_404(Tag, name=tag)
    quotes = Quote.objects.all()
    return render(request, "appquote/tag.html", {"tag": tags, "quotes": quotes})

homework/quotes/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='appquote:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='appquote:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect('main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='appquote:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='appquote:main')

homework/quotes/appquote/templates/appquote/addauthor.html
{% extends "appquote/base.html" %}

{% block content %}

<form method="POST" action="{% url 'appquote:addauthor' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author full name:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author description:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

homework/quotes/appquote/templates/appquote/addquote.html
{% extends "appquote/base.html" %}

{% block content %}

<form method="POST" action="{% url 'appquote:addquote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.text }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>

    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div style="padding: 10px">
        <label> Select Author:
            <select name="author">
                {% for author in authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

homework/quotes/appquote/templates/appquote/addtag.html
{% extends "appquote/base.html" %}

{% block content %}

<form method="POST" action="{% url 'appquote:addtag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

homework/quotes/appquote/templates/appquote/author.html
{% extends "appquote/base.html" %}

{% block content %}

<h4>{{ author.fullname }}</h4>
Born {{ author.born_date }} {{ author.born_location }}
<hr>
<h4>About author</h4>
{{ author.description }}

{% endblock %}

homework/quotes/appquote/templates/appquote/base.html
<!DOCTYPE html>
<html lang="en">

<title>Quotes</title>

<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body>

    <main class="container">

        {% if user.is_authenticated %}
        <a class="nav-link active" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/addauthor">Add author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/addtag">Add tag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/addquote">Add quote</a>
                        </li>
                    </ul>

                </div>
            </div>

            {% else %}
            <a class="enter" href="/users/signup">Sign up</a>
            OR
            <a class="enter" href="/users/login">Login</a>
            {% endif %}
        </nav>

        {% block content %} {% endblock %}

    </main>
</body>

</html>

homework/quotes/appquote/templates/appquote/index.html
{% extends "appquote/base.html" %}

{% block content %}

<hr>
<h2>Top tags</h2>

{% for el in most_popular_tag %}
<a href="tag/{{ el }}" class="btn btn-primary">|{{ el }}|</a>
{% endfor %}
<hr>

<h2>All quotes</h2>

{% for el in page_obj %}

<div class="card" ,>
    <div class="card-body">
        <strong class="author-name">{{ el.show_quote_author }}</strong>
        <a href="author/{{ el.show_quote_author }}" class="btn btn-primary">More about author</a>
        <p class="card-text">{{ el.show_quote_text }}</p>
        {% for tag in el.show_quote_tags %}
        <a href="tag/{{ tag }}" class="btn btn-primary">|{{ tag }}|</a>
        {% endfor %}
        <hr>
    </div>
</div>
{% endfor %}

<nav>
    <ul>
        {% for p in page_obj.paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
        {% else %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock %}

homework/quotes/appquote/templates/appquote/tag.html
{% extends "appquote/base.html" %}


{% block content %}

<h4>All quotes for tag {{ tag }} </h4>
<hr>

{% for quote in quotes %}
{% if tag in quote.show_quote_tags %}
<div class="card" ,>
    <div class="card-body">
        <strong class="author-name">{{ quote.show_quote_author }}</strong>
        <a href="/author/{{ quote.show_quote_author }}" class="btn btn-primary">More about author</a>
        <p class="card-text">{{ quote.show_quote_text }}</p>
        {% for tag in quote.show_quote_tags %}
        <a href="/tag/{{ tag }}" class="btn btn-primary">|{{ tag }}|</a>
        {% endfor %}
        <hr>
    </div>
</div>
{% endif %}
{% endfor %}


{% endblock %}

homework/quotes/users/templates/users/login.html
{% extends "appquote/base.html" %}

{% block content %}
<title>Login</title>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

homework/quotes/users/templates/users/signup.html
{% extends "appquote/base.html" %}

{% block content %}
<title>Sign Up</title>

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}